name: fetch-blogs-from-medium
run-name: Scrapping Pranshu's Medium blog
on:
  schedule:
    - cron: "45 12 * * *" # run 7:30 AM IST everyday
permissions:
  contents: write
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # git checkout
      - uses: actions/checkout@v2
        with:
          ref: master
          # repository: "Pranshu1902p/Pranshu1902p.github.io"
      # setup python
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      # installing the dependencies
      - name: install dependencies
        run: |
          python -m pip install 'requests'
          python -m pip install 'bs4'
      # running the script
      - name: execute py script
        run: |
          python ./.github/workflows/mediumBlogsFetch.py
      # pushing the update code
      - name: switching from HTTPS to SSH
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: check for changes
        run: git status
      - name: stage changed files
        run: git add .
      - name: commit changed files
        run: git commit -m "🌍 Update JSON- Web Scrap Blogs from Medium - $(date -d '+5 hours +30 minutes' +'%d %b %Y | %I:%M %p')"
      - name: fetch from master
        run: git fetch origin master
      # authentication details
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master

      # - name: Build for github pages
      #   run: |
      #     npm i
      #     npm run build

      # - name: Deploy 🚀
      #   uses: JamesIves/github-pages-deploy-action@v4
      #   with:
      #     folder: build
