name: fetch-blogs-from-medium
run-name: Scrapping Pranshu's Medium blog
on:
  schedule:
    - cron: "25 14 * * *" # run script after everyday
permissions:
  contents: write
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # checkout actions
      - uses: actions/checkout@v3
      # setup python
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      # installing the dependencies
      - name: install dependencies
        run: |
          python -m pip install 'requests'
          python -m pip install 'bs4'
      # running the script
      - name: execute py script
        run: |
          python ./.github/workflows/mediumBlogsFetch.py
      # pushing the update code
      - name: switching from HTTPS to SSH
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: check for changes
        run: git status
      - name: stage changed files
        run: git add .
      - name: commit changed files
        run: git commit -m "🌍 Update JSON- srap blogs from medium"
      - name: fetch from master
        run: git fetch origin master
      # authentication details
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
